# 数组创建函数
- array：将输入的数据（列表、元组、数组或其他序列类型）转换为ndarray，默认直接复制输入数据
- asarray：将输入转换为ndarray，如果输入本身就是一个ndarray就不进行复制
- arange：类似于range函数，返回的是一个ndarray
- ones/ones_like：根据指定的形状和dtype创建一个元素全为1的数组。ones_like以另一个数组为参照，并根据其形状和dtype创建一个全1数组
- empty/empty_like：创建数组，只分配内存空间但不填充任何值
- eye/identity：创建一个N维的单位矩阵

In [42]:
import numpy as np
arr1 = np.zeros(5)
print(arr1)
print(type(arr1))
print(arr1.ndim)              # 查看数组的维数
print(arr1.shape)             # 查看数组的“形状”
print(arr1.dtype)             # 查看数组中数据的类型

print("*" * 20)

a = [1,2,3,4,5]
arr2 = np.array(a)
print(arr2)
print(type(arr2))
print(arr2.ndim)
print(arr2.shape)
print(arr2.dtype)

print("*" * 20)

b = [[1,2,3], [4,5,6]]
arr3 = np.array(b)
print(arr3)
print(type(arr3))
print(arr3.ndim)
print(arr3.shape)
print(arr3.dtype)

print("*" * 20)

np.zeros((3,6))

[0. 0. 0. 0. 0.]
<class 'numpy.ndarray'>
1
(5,)
float64
********************
[1 2 3 4 5]
<class 'numpy.ndarray'>
1
(5,)
int32
********************
[[1 2 3]
 [4 5 6]]
<class 'numpy.ndarray'>
2
(2, 3)
int32
********************


array([[0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0.]])

In [48]:
import numpy as np
np.empty((2,3,2))          # np.empty不会产生全为0的数组，很多情况下，返回的都是一些未初始化的垃圾值

array([[[3.42450058e-312, 3.16202013e-322],
        [0.00000000e+000, 0.00000000e+000],
        [0.00000000e+000, 1.00606403e-070]],

       [[1.16436563e+165, 3.54206536e-033],
        [2.21757775e-056, 5.94220227e-038],
        [1.77496771e+160, 1.05118866e-046]]])

- 可以通过ndarray的astype方法来转换其dtype

In [9]:
import numpy as np

arr = np.array([1,2,3,4,5])
print(arr.dtype)

float_arr = arr.astype(np.float64)
float_arr.dtype

int32


dtype('float64')

In [6]:
# 若将浮点型数据转换为整型的，则小数部分将会被截断
import numpy as np

arr = np.array([1.2, 2.3, -4.4, 5.5534])
int_arr = arr.astype(np.int32)
int_arr

array([ 1,  2, -4,  5])

In [8]:
# 若某字符串数组表示的全是数字，也可以用astype将其转换为数值形式
import numpy as np

numeric_strings = np.array(["1.23", "-9.5", "24"])
float_arr = numeric_strings.astype(float)                  # 这里使用的是float，而非具体指定其形式，numpy会根据内容分配等价的dtype上
float_arr

array([ 1.23, -9.5 , 24.  ])

In [20]:
# dtype的另一种用法
import numpy as np

int_arr = np.arange(10)
float_arr = np.array([1.2, 0.344, 23.234], dtype = np.float64)        # 可以用此方法指定所创建数组的元素类型
int_arr.astype(float_arr.dtype)
int_arr2 = int_arr
int_arr2

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

# 数组的内容修改
- numpy中对数组内容进行修改，都会直接反应到原数组上
- 若想要得到的是ndarray切片的一份副本而非视图，就需要显式的进行复制操作
    例如：arr[5:8].copy()

# 布尔型索引

In [1]:
import numpy as np
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.arange(28).reshape((7,4))
print(names == "Bob")
print(data[names == "Bob"])
print(data[names == "Bob", 3])
print(data[names == "Bob", 2:])

[ True False False  True False False False]
[[ 0  1  2  3]
 [12 13 14 15]]
[ 3 15]
[[ 2  3]
 [14 15]]


In [3]:
import numpy as np
names = np.array(["Bob", "Joe", "Will", "Bob", "Will", "Joe", "Joe"])
data = np.random.randn(7,4)
print(data)
print("*" * 20)
data[data < 0] = 0
print(data)

[[ 0.0357944  -1.94570355  0.90641333 -0.66279834]
 [ 1.20504437 -0.51224477 -0.87102946  0.05993234]
 [-0.15967717 -0.79550382 -0.43488206 -1.25550323]
 [-0.13560845  1.69362283 -0.32656467 -1.1022595 ]
 [ 0.01879409  0.55601123 -0.86532093 -2.79497816]
 [ 1.17905221  1.46641746  0.61076371  0.23421291]
 [-0.242522    0.14913877 -0.04419354  0.33670689]]
********************
[[0.0357944  0.         0.90641333 0.        ]
 [1.20504437 0.         0.         0.05993234]
 [0.         0.         0.         0.        ]
 [0.         1.69362283 0.         0.        ]
 [0.01879409 0.55601123 0.         0.        ]
 [1.17905221 1.46641746 0.61076371 0.23421291]
 [0.         0.14913877 0.         0.33670689]]


- 在Python的numpy库中，逻辑and和or在布尔型数组中是无效的

# 花式索引
- 为了以特定顺序选取行子集，只需传入一个用于指定顺序的整数列表或ndarray即可

In [4]:
import numpy as np
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)
print("*" * 20)
print(arr[[4,3,0,6]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
********************
[[4. 4. 4. 4.]
 [3. 3. 3. 3.]
 [0. 0. 0. 0.]
 [6. 6. 6. 6.]]


In [5]:
import numpy as np
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i + 1
print(arr)
print("*" * 20)
print(arr[[4,3,0,6]])

[[1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]
 [8. 8. 8. 8.]]
********************
[[5. 5. 5. 5.]
 [4. 4. 4. 4.]
 [1. 1. 1. 1.]
 [7. 7. 7. 7.]]


In [6]:
import numpy as np
arr = np.empty((8,4))
for i in range(8):
    arr[i] = i
print(arr)
print("*" * 20)
print(arr[[-1,-3,-5]])

[[0. 0. 0. 0.]
 [1. 1. 1. 1.]
 [2. 2. 2. 2.]
 [3. 3. 3. 3.]
 [4. 4. 4. 4.]
 [5. 5. 5. 5.]
 [6. 6. 6. 6.]
 [7. 7. 7. 7.]]
********************
[[7. 7. 7. 7.]
 [5. 5. 5. 5.]
 [3. 3. 3. 3.]]


In [8]:
# 利用reshape来重新排列创建的数组
import numpy as np
arr = np.arange(32).reshape((8,4))
print(arr)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]
 [16 17 18 19]
 [20 21 22 23]
 [24 25 26 27]
 [28 29 30 31]]


In [13]:
# 对于以下的程序，选出的元素为（1,0）、（5,3）、（7,1）和（2，2），而非所想的四行四列
print(arr[[1,5,7,2],[0,3,1,2]])

[ 4 23 29 10]


In [10]:
# 下面是得到想要结果的一种方法
arr[[1,5,7,2]][:, [0,3,1,2]]

array([[ 4,  7,  5,  6],
       [20, 23, 21, 22],
       [28, 31, 29, 30],
       [ 8, 11,  9, 10]])

In [11]:
# 另一个方法为使用np.ix_函数，它可以将两个一维整数数组转换成一个用于选取方形区域的索引器
print(arr[np.ix_([1,5,7,2], [0,3,1,2])])

[[ 4  7  5  6]
 [20 23 21 22]
 [28 31 29 30]
 [ 8 11  9 10]]


# 数组转置和轴对换

In [14]:
import numpy as np
arr = np.arange(15).reshape((3,5))
print(arr)
print("*" * 20)
print(arr.T)

[[ 0  1  2  3  4]
 [ 5  6  7  8  9]
 [10 11 12 13 14]]
********************
[[ 0  5 10]
 [ 1  6 11]
 [ 2  7 12]
 [ 3  8 13]
 [ 4  9 14]]
